# ===================================
#  Extended Profile Field Definitions
# ===================================

fraction_digits:
    label: "initbiz.money::lang.currency_form.fraction_digits"
    type: number
    span: left
    default: 2
